hmm_opts = {'hidden_state_size' : 100,
           'covariance_type' : 'spherical', 
           'fit_params' : 'stm',
           'transmat_prior' : 1.,
           'n_iter' : 300,
           'tolerance' : 0.01,
           'nz' : 16, 
           'ngf' : 264,
           'nc' : 1,
            'covars_prior' : 1.,
            'imageH': 129,
           'imageW': 16,
           'batchsize' : 2,
            'train_proportion' : 0.7,
           'nsamplesteps' : 128,
           'nsamps': 10,
           'sample_var': 0.1,
            'sample_invtemperature' : 1.,
            'init_cov': 0.1,
            'n_restarts': 10,
            'do_chaining': False,
            'min_seq_multiplier': 10
           }